РК-1
frontend-park-mail-ru/2021_2_Good_Vibes pull request #3
Opened 2021-09-28 11:55 UTC by KadyrovSuleyman

Команда GoodVibes, проект Ozon2.0

2021-09-28 21:31 UTC, zelflod requested changes

2021-09-28 21:31 UTC, zelflod commented on public/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
нельзя использовать сторонние библиотеки

2021-09-28 21:31 UTC, zelflod commented on server/index.js
> +'use strict';
если этот файл больше не используете, то можно удалить

2021-09-28 21:52 UTC, zelflod requested changes

2021-09-28 21:52 UTC, zelflod commented on .eslintrc.js
> +    "env": {
кроме конфига линтера в package.json должна быть команда для запуска линтера

что-то такое
"scripts": {
		"lint": "npx eslint public/src**",
	},

2021-09-28 21:52 UTC, zelflod commented on .eslintrc.js
> +    "env": {
добавьте @babel/core и babel-eslint в devDependencies

2021-09-29 01:03 UTC, KadyrovSuleyman commented on public/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
исправлено

2021-09-29 01:03 UTC, KadyrovSuleyman commented on server/index.js
> +'use strict';
исправлено

2021-09-29 01:03 UTC, KadyrovSuleyman commented on .eslintrc.js
> +    "env": {
исправлено

2021-09-29 08:29 UTC, merged